let quotes = [
    "The purpose of our lives is to be happy.",
    "Life is what happens when you are busy making other plans.", 
    "Get busy living or get busy dying.",
   "You only live once, but if you do it right, once is enough.",
   "Many of life’s failures are people who did not realize how close they were to success when they gave up.",
   "If you want to live a happy life, tie it to a goal, not to people or things.",
   "Never let the fear of striking out keep you from playing the game.",
   "Money and success don’t change people; they merely amplify what is already there.", 
    "Your time is limited, so don’t waste it living someone else’s life.", 
    "Don’t be trapped by dogma – which is living with the results of other people’s thinking.",    
   "Not how long, but how well you have lived is the main thing.",
    "If life were predictable it would cease to be life, and be without flavor.",
   "The whole secret of a successful life is to find out what is one’s destiny to do, and then do it.", 
   "In order to write about life first you must live it.",
   "The big lesson in life, baby, is never be scared of anyone or anything.",    
   "Sing like no one’s listening, love like you’ve never been hurt, dance like nobody’s watching, and live like it’s heaven on earth.",
   "Curiosity about life in all of its aspects, I think, is still the secret of great creative people.",   
   "Life is not a problem to be solved, but a reality to be experienced.",
   "The unexamined life is not worth living.",
   "Turn your wounds into wisdom.",
   "The way I see it, if you want the rainbow, you gotta put up with the rain.",   
   "Do all the good you can, for all the people you can, in all the ways you can, as long as you can.",
   "Don’t settle for what life gives you; make life better and build something.",  
   "Everything negative – pressure, challenges – is all an opportunity for me to rise.",   
   "I like criticism. It makes you strong.",    
   "You never really learn much from hearing yourself speak.",
   "Life imposes things on you that you can’t control, but you still have the choice of how you’re going to live through this.",   
   "Life is never easy. There is work to be done and obligations to be met – obligations to truth, to justice, and to liberty.",
   "Live for each second without hesitation.",  
   "Life is like riding a bicycle. To keep your balance, you must keep moving.",
   "Life is really simple, but men insist on making it complicated.", 
   "Life is a succession of lessons which must be lived to be understood.",    
   "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
   "My mama always said, life is like a box of chocolates. You never know what you’re gonna get.",
   "Watch your thoughts; they become words. Watch your words; they become actions. Watch your actions; they become habits. Watch your habits; they become character. Watch your character; it becomes your destiny.", 
   "When we do the best we can, we never know what miracle is wrought in our life or the life of another.",    
   "The healthiest response to life is joy.",
   "Life is like a coin. You can spend it any way you wish, but you only spend it once.",
   "The best portion of a good man’s life is his little nameless, unencumbered acts of kindness and of love.",  
   "In three words I can sum up everything I’ve learned about life: It goes on.",    
   "Life is ten percent what happens to you and ninety percent how you respond to it.",
   "Keep calm and carry on.",
   "Maybe that’s what life is… a wink of the eye and winking stars.",    
   "Life is a flower of which love is the honey.",   
   "Keep smiling, because life is a beautiful thing and there’s so much to smile about.",
   "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.", 
   "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.", 
   "Good friends, good books, and a sleepy conscience: this is the ideal life.",  
   "Life would be tragic if it weren’t funny.",
   "Live in the sunshine, swim the sea, drink the wild air.",
   "The greatest pleasure of life is love.", 
   "Life is what we make it, always has been, always will be.",
   "Life’s tragedy is that we get old too soon and wise too late.",
   "Life is about making an impact, not making an income.",   
   "I’ve missed more than 9000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life. And that is why I succeed.",
   "Every strike brings me closer to the next home run.", 
   "The two most important days in your life are the day you are born and the day you find out why.",  
   "Life shrinks or expands in proportion to one’s courage.", 
   "Too many of us are not living our dreams because we are living our fears.", 
   "I believe every human has a finite number of heartbeats. I don’t intend to waste any of mine.", 
   "Live as if you were to die tomorrow. Learn as if you were to live forever.",
   "If you live long enough, you’ll make mistakes. But if you learn from them, you’ll be a better person.",   
   "Life is short, and it is here to be lived.",    
   "The longer I live, the more beautiful life becomes.",
   "Every moment is a fresh beginning.", 
   "When you cease to dream you cease to live.",
   "If you spend your whole life waiting for the storm, you’ll never enjoy the sunshine.",  
   "Don’t cry because it’s over, smile because it happened.", 
   "If you can do what you do best and be happy, you’re further along in life than most people.",
   "We should remember that just as a positive outlook on life can promote good health, so can everyday acts of kindness.",
   "Don’t limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you. What you believe, remember, you can achieve.",    
       "It is our choices that show what we truly are, far more than our abilities.",    
   "If you’re not stubborn, you’ll give up on experiments too soon. And if you’re not flexible, you’ll pound your head against the wall and you won’t see a different solution to a problem you’re trying to solve.", 
   "The best way to predict your future is to create it.",
   "You must expect great things of yourself before you can do them.",
   "Identity is a prison you can never escape, but the way to redeem your past is not to run from it, but to try to understand it, and use it as a foundation to grow.",
   "There are no mistakes, only opportunities.",
   "It takes 20 years to build a reputation and five minutes to ruin it. If you think about that, you’ll do things differently.",
   "As you grow older, you will discover that you have two hands, one for helping yourself, the other for helping others.",
   "Sometimes you can’t see yourself clearly until you see yourself through the eyes of others.",
   "You must not lose faith in humanity. Humanity is an ocean; if a few drops of the ocean are dirty, the ocean does not become dirty.", 
   "All life is an experiment. The more experiments you make, the better.",
   "It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them. They went out and happened to things.",
   "Throughout life people will make you mad, disrespect you and treat you bad. Let God deal with the things they do, cause hate in your heart will consume you too.",  
   "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
   "Life is a dream for the wise, a game for the fool, a comedy for the rich, a tragedy for the poor.",
   "If you love life, don’t waste time, for time is what life is made up of.",   
   "Never take life seriously. Nobody gets out alive anyway.", 
   "Be happy for this moment. This moment is your life.",    
   "Happiness is the feeling that power increases — that resistance is being overcome.",  
   "I have learned to seek my happiness by limiting my desires, rather than in attempting to satisfy them.",  
   "The secret of happiness, you see is not found in seeking more, but in developing the capacity to enjoy less.",
   "The more man meditates upon good thoughts, the better will be his world and the world at large.", 
   "The greatest blessings of mankind are within us and within our reach. A wise man is content with his lot, whatever it may be, without wishing for what he has not.",
   "When it is obvious that goals can’t be reached, don’t adjust the goals, but adjust the action steps.", 
   "There may be people who have more talent than you, but there’s no excuse for anyone to work harder than you do – and I believe that.",   
   "Don’t be afraid to fail. It’s not the end of the world, and in many ways, it’s the first step toward learning something and getting better at it.",
   "Life is very interesting… in the end, some of your greatest pains, become your greatest strengths.",
   "I think if you live in a black-and-white world, you’re gonna suffer a lot. I used to be like that. But I don’t believe that anymore.",
   "I don’t believe in happy endings, but I do believe in happy travels, because ultimately, you die at a very young age, or you live long enough to watch your friends die. It’s a mean thing, life.",
   "It’s never too late – never too late to start over, never too late to be happy.",  
   "You’re only human. You live once and life is wonderful, so eat the damned red velvet cupcake.",  
   "A lot of people give up just before they’re about to make it. You know you never know when that next obstacle is going to be the last one.",
   "Be nice to people on the way up, because you may meet them on the way down.",
   "I believe you make your day. You make your life. So much of it is all perception, and this is the form that I built for myself. I have to accept it and work within those compounds, and it’s up to me.", 
   "The minute that you’re not learning I believe you’re dead.",
   "Life’s tough, but it’s tougher when you’re stupid.",  
   "Take up one idea. Make that one idea your life — think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body be full of that idea, and just leave every other idea alone. This is the way to success.",
   "I guess it comes down to a simple choice, really. Get busy living or get busy dying.",
   "When we strive to become better than we are, everything around us becomes better too.",
   "There are three things you can do with your life: You can waste it, you can spend it, or you can invest it. The best use of your life is to invest it in something that will last longer than your time on Earth.",   
   "You only pass through this life once, you don’t come back for an encore.",
   "In the long run, the sharpest weapon of all is a kind and gentle spirit.",  
   "You’re not defined by your past; you’re prepared by it. You’re stronger, more experienced, and you have greater confidence.",   
   "We become not a melting pot but a beautiful mosaic. Different people, different beliefs, different yearnings, different hopes, different dreams.",    
   "Nothing is more honorable than a grateful heart.",   "Once you figure out who you are and what you love about yourself, I think it all kinda falls into place.",
   "Happy is the man who can make a living by his hobby.",
   "Just disconnect. Once in a day sometime, sit silently and from all connections disconnect yourself.",
   "Be where you are; otherwise you will miss your life.",  
    "Living an experience, a particular fate, is accepting it fully.",    
   "The more you praise and celebrate your life, the more there is in life to celebrate.",
   "Your image isn’t your character. Character is what you are as a person.",   
   "Football is like life, it requires perseverance, self-denial, hard work sacrifice, dedication and respect for authority.",
   "As you know, life is an echo; we get what we give.",
   "There are no regrets in life, just lessons.",
   "I believe that nothing in life is unimportant every moment can be a beginning.",   
   "Find people who will make you better.",
   "As my knowledge of things grew I felt more and more the delight of the world I was in.",    
   "Benjamin Franklin was a humanitarian that dedicated his life to making contributions to all humans. He had a clear purpose for himself: improve the human race.",   
   "You cannot control everything that happens to you; you can only control the way you respond to what happens. In your response is your power.", 
   "Don’t allow your past or present condition to control you. It’s just a process that you’re going through to get you to the next level.",  
   "You will meet two kinds of people in life: ones who build you up and ones who tear you down. But in the end, you’ll thank them both.", 
   "My mission in life is not merely to survive, but to thrive; and to do so with some passion, some compassion, some humor, and some style.",    
   "If we don’t change, we don’t grow. If we don’t grow, we aren’t really living.",   
   "You choose the life you live. If you don’t like it, it’s on you to change it because no one else is going to do it for you.",    
   "It is impossible to live without failing at something, unless you live so cautiously, that you might as well not have lived at all – in which case you fail by default.", 
   "Life doesn’t require that we be the best, only that we try our best.",
   "The way I see it, every life is a pile of good things and bad things. The good things don’t always soften the bad things, but vice versa, the bad things don’t always spoil the good things and make them unimportant.",  
   "Life isn’t about waiting for the storm to pass, it’s about learning to dance in the rain.",
   "I enjoy life when things are happening. I don’t care if it’s good things or bad things. That means you’re alive.",   
   "There’s more to life than basketball. The most important thing is your family and taking care of each other and loving each other no matter what.",
   "Today, you have 100% of your life left.",
   "Nobody who ever gave his best regretted it.",    
   "Make each day your masterpiece.",   
   "You can’t put a limit on anything. The more you dream, the farther you get." ,
   "Friendship is the hardest thing in the world to explain. It’s not something you learn in school. But if you haven’t learned the meaning of friendship, you really haven’t learned anything.",
    "Don’t make friends who are comfortable to be with. Make friends who will force you to lever yourself up.",
    "The most beautiful discovery true friends make is that they can grow separately without growing apart.",
    "Each friend represents a world in us, a world possibly not born until they arrive, and it is only by this meeting that a new world is born.",
    "They may forget what you said, but they will never forget how you made them feel.",
    "Find a group of people who challenge and inspire you; spend a lot of time with them, and it will change your life.",
    "For beautiful eyes, look for the good in others; for beautiful lips, speak only words of kindness; and for poise, walk with the knowledge that you are never alone.",
    "The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart.",
    "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.",
    "A friend is someone who understands your past, believes in your future, and accepts you just the way you are.",
    "Let us be grateful to the people who make us happy; they are the charming gardeners who make our souls blossom.",
    "Lots of people want to ride with you in the limo, but what you want is someone who will take the bus with you when the limo breaks down.",
    "In the sweetness of friendship let there be laughter, for in the dew of little things the heart finds its morning and is refreshed.",
    "It’s not what we have in life, but who we have in our life that matters.",
    "A friend is one who overlooks your broken fence and admires the flowers in your garden.",
    "friend who understands your tears is much more valuable than a lot of friends who only know your smile.",
    "weren’t sisters [or brothers] by birth, but we knew from the start…fate brought us together to be sisters [or brothers] by heart.",
    "friend is one of the best things you can be and the greatest things you can have.",
    "Best friends are the people in your life who make you laugh louder, smile brighter and live better.",
    "me doesn’t take away from friendship, nor does separation.",
    "When the world is so complicated, the simple gift of friendship is within all of our hands.",
    "There’s not a word yet for old friends who’ve just met.","A single rose can be my garden…a single friend, my world.",
    "Friendship is the only cement that will ever hold the world together.",
    "Friends are those rare people who ask how we are and then wait to hear the answer.",
    "A friend knows the song in my heart and sings it to me when my memory fails.",
    "It’s the friends you can call up at 4 a.m. that matter.",
    "Truly great friends are hard to find, difficult to leave, and impossible to forget.","A good friend is like a four-leaf clover; hard to find and lucky to have.",
    "I would rather walk with a friend in the dark, than alone in the light.",
    "True friends are never apart, maybe in distance but never in heart.",
    "No friendship is an accident.",
    "ometimes being with your best friend is all the therapy you need.", 
    "iends are the siblings God never gave us.",
    "ue friends are like diamonds — bright, beautiful, valuable, and always in style.",
    "There is nothing on this earth more to be prized than true friendship.",
    "Friends are the family you choose.",
    "Anything is possible when you have the right people there to support you.",
    "A sweet friendship refreshes the soul.",
    "Life was meant for good friends and great adventures.",
    "Best friend: the one that you can be mad at only for a short period of time because you have important stuff to tell them.",
    ",ere is nothing better than a friend, unless it is a friend with chocolate.",
    "‘Tis the privilege of friendship to talk nonsense, and to have her nonsense respected.",
    "A true friend is someone who thinks that you are a good egg even though he knows that you are slightly cracked.",
    "A true friend never gets in your way unless you happen to be going down.",
    "A best friend is someone who makes you laugh even when you think you’ll never smile again.",
    "st friends. Because if anyone else heard our conversations we’d end up in the mental hospital.",
    "st friends don’t care if your house is clean. They care if you have wine.", 
    "you are ever lucky enough to find a weirdo, never let them go.",
    "Friendship is so weird…you just pick a human you’ve met and you’re like ‘Yep, I like this one’ and you just do stuff with them.",
    "Ultimately the bond of all companionship, whether in marriage or in friendship, is conversation.",
    "A friend is a person with whom I may be sincere. Before him I may think aloud. I am arrived at last in the presence of a man so real and equal, that I may drop even those undermost garments of dissimulation, courtesy, and second thought, which men never put off, and may deal with him with the simplicity and wholeness with which one chemical atom meets another.",
    "In everyone’s life, at some time, our inner fire goes out. It is then burst into flame by an encounter with another human being. We should all be thankful for those people who rekindle the inner spirit.",
    "Real friendship, like real poetry, is extremely rare — and precious as a pearl.",
    "But friendship is precious, not only in the shade, but in the sunshine of life, and thanks to a benevolent arrangement the greater part of life is sunshine.",
    "When we honestly ask ourselves which person in our lives means the most to us, we often find that it is those who, instead of giving advice, solutions, or cures, have chosen rather to share our pain and touch our wounds with a warm and tender hand.",
    "A friend may be waiting behind a stranger’s face.",
    "Everyone you meet knows something you don’t know but need to know. Learn from them.","Don’t be afraid of new beginnings. Don’t shy away from new people, new energy, new surroundings. Embrace new chances at happiness.",
    "Each new friendship can make you a new person, because it opens up new doors inside of you.",
    "Be genuinely interested in everyone you meet and everyone you meet will be genuinely interested in you.",
    "Since there is nothing so well worth having as friends, never lose a chance to make them.",
    "Every new friend is a new adventure… the start of more memories.",
    "The great thing about new friends is that they bring new energy to your soul.",
    "The kindest way of helping yourself is to find a friend.",
    "Getting to know new people and gaining new friends is one of life’s greatest pleasures. So conquer your fears and get out there.","There are friendships imprinted in our hearts that will never be diminished by time and distance.",
    "o distance of place or lapse of time can lessen the friendship of those who are thoroughly persuaded of each other’s worth.",
    "There is magic in long-distance friendships. They let you relate to other human beings in a way that goes beyond being physically together and is often more profound.",
    "A part of you has grown in me, together forever we shall be, never apart, maybe in distance, but not in heart.",
    "Distance means so little, when someone means so much.","If there ever comes a day when we can’t be together, keep me in your heart. I’ll stay there forever.",
    "As long as we share the same sky and breathe the same air, we’re still together.",
    "A friend who is far away is sometimes much nearer than one who is at hand.",
    "Can miles truly separate you from friends…If you want to be with someone you love, aren’t you already there?",
    "A strong friendship doesn’t need daily conversation, doesn’t always need togetherness, as long as the relationship lives in the heart, true friends will never part.",
]